"""
Pydantic Data Models for Multi-Agent Orchestration & Planner (Phase 10).
"""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, field_validator


class PlannerPlan(BaseModel):
    """Structured plan produced by Planner Agent classifying query intent & tools."""

    intent: str = Field(..., description="Classified query intent category (e.g. sql_query, rag_search, combined, analytics, visualization, general)")
    requires_sql: bool = Field(default=False, description="True if database SQL query execution is required")
    requires_rag: bool = Field(default=False, description="True if semantic document search is required")
    requires_analytics: bool = Field(default=False, description="True if statistical computation is required")
    requires_visualization: bool = Field(default=False, description="True if chart/visualization is required")
    reason: str = Field(..., description="Concise justification for selected capabilities")


class AskRequest(BaseModel):
    """Client API Request payload for natural language orchestration."""

    question: str = Field(..., min_length=3, max_length=1000, description="User business question")

    @field_validator("question")
    @classmethod
    def validate_question_not_empty(cls, v: str) -> str:
        cleaned = v.strip()
        if not cleaned:
            raise ValueError("Question cannot be empty or whitespace.")
        return cleaned


class AskResponse(BaseModel):
    """Structured response payload returned by OrchestrationService."""

    request_id: str = Field(..., description="Unique correlation ID for orchestration run")
    question: str = Field(..., description="Original user question")
    status: str = Field(default="completed", description="Overall execution status: completed, partial, or failed")
    plan: PlannerPlan = Field(..., description="Execution plan generated by Planner Agent")
    results: Dict[str, Any] = Field(default_factory=dict, description="Structured outputs from executed tool agents (sql, rag, analytics, visualization)")
    errors: List[str] = Field(default_factory=list, description="Non-fatal warnings or error messages encountered during execution")
    execution_time_ms: float = Field(default=0.0, description="Total orchestration duration in milliseconds")
