"""
Pydantic Schemas for EMBIP Analytics Agent (Phase 11).
Defines input contract, result schema, and LLM intent classification format.
"""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class AnalyticsInput(BaseModel):
    """Structured input contract for analytics operation execution."""

    columns: List[str] = Field(..., description="List of dataset column names.")
    rows: List[Dict[str, Any]] = Field(..., description="List of row dictionaries.")
    operation: str = Field(..., description="Analytics operation name from registry.")
    metric_column: Optional[str] = Field(None, description="Primary numerical column for calculation.")
    group_by: Optional[str] = Field(None, description="Column name for grouped aggregations.")
    time_column: Optional[str] = Field(None, description="Column name containing timestamps/dates.")
    parameters: Dict[str, Any] = Field(default_factory=dict, description="Operation parameters (e.g. n, period, window).")


class AnalyticsSummary(BaseModel):
    """Data quality and execution summary for analytics run."""

    rows_input: int = Field(..., description="Total input rows passed to analytics.")
    rows_used: int = Field(..., description="Valid rows used in calculation.")
    missing_values: int = Field(0, description="Count of NaN/Null or invalid missing values skipped.")
    warnings: List[str] = Field(default_factory=list, description="Data quality or calculation warnings.")


class AnalyticsProvenance(BaseModel):
    """Source data lineage tracking for auditability."""

    sql_request_id: Optional[str] = Field(None, description="Associated SQL execution query ID.")
    workspace_id: Optional[str] = Field(None, description="Workspace ID context.")
    source_columns: List[str] = Field(default_factory=list, description="Original columns used.")
    source_row_count: int = Field(0, description="Original source dataset size.")


class AnalyticsGroupResult(BaseModel):
    """Single item in grouped aggregation output."""

    group: Any = Field(..., description="Group key value.")
    value: Any = Field(..., description="Computed metric value for group.")


class AnalyticsSeriesPoint(BaseModel):
    """Single point in time-series analytical output."""

    period: str = Field(..., description="Formated time period string (e.g. '2025-01', '2025-W04').")
    value: Any = Field(..., description="Aggregated metric value for period.")


class AnalyticsResult(BaseModel):
    """Structured result model returned by Analytics Service."""

    operation: str = Field(..., description="Executed operation name.")
    status: str = Field(..., description="'success', 'warning', or 'error'")
    metric: Optional[str] = Field(None, description="Target metric column name.")
    value: Optional[Any] = Field(None, description="Scalar numerical or boolean calculation result.")
    groups: Optional[List[AnalyticsGroupResult]] = Field(None, description="List of grouped results if applicable.")
    series: Optional[List[AnalyticsSeriesPoint]] = Field(None, description="Time series points if applicable.")
    summary: AnalyticsSummary = Field(..., description="Summary data quality metrics.")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Metadata dictionary.")
    provenance: Optional[AnalyticsProvenance] = Field(None, description="Data provenance lineage.")
    explanation: Optional[str] = Field(None, description="Natural-language interpretation generated by LLM.")
    error: Optional[str] = Field(None, description="Error message string if status is 'error'.")


class AnalyticsIntentClassification(BaseModel):
    """Structured output format for LLM intent classification."""

    operation: str = Field(..., description="Operation registry key selected.")
    metric_column: Optional[str] = Field(None, description="Selected metric column name.")
    group_by: Optional[str] = Field(None, description="Selected group-by column name.")
    time_column: Optional[str] = Field(None, description="Selected time/date column name.")
    parameters: Dict[str, Any] = Field(default_factory=dict, description="Extracted operation parameters.")
    reasoning: str = Field(..., description="Rationale for operation and column selection.")
